name = "discord-kudos"
account_id = "82addaa9d26595c050e09ffc1522646f"
# route = ""
workers_dev = true
compatibility_date = "2022-05-25"
main = "src/index.ts"
node_compat = true

[build]
command = "pnpm install && pnpm run build"

[[durable_objects.bindings]]
name = "kudos"
class_name = "Kudos"

[[migrations]]
tag = "v1"
new_classes = ["Kudos"]
